create table
  public.contact (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    salutation text null,
    first_name text null,
    middle_name text null,
    last_name text null,
    address1 text null,
    address2 text null,
    city text null,
    pin_code text null,
    state text null,
    country text null,
    gender character varying null,
    is_active boolean null default true,
    mobile text null,
    email text null,
    constraint contact_pkey primary key (id)
  ) tablespace pg_default;